spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1
                - AddResponseHeader=X-Gateway, gateway-server

            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - StripPrefix=1
                - AddResponseHeader=X-Gateway, gateway-server

server:
  port: 9120

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/

  instance:
    prefer-ip-address: true