management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C
    export:
      zipkin:
        enabled: true
        endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  include-application-name: false
  pattern:
    correlation: "[${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}] "
